### ISSUE TITLE
Error Message when moving from 'Move to' to 'Control'

### ISSUE THREAD

**Issue by flopitters** [hephy-dd/comet-pqc#53]
When moving to manual controls via the 'Control' dialog immediately after using the 'Move to' dialog, the 'Control dialog' closes with 'Error: 1004 '. After reopening the 'Control' dialog, all works fine. 

Version: 0.21.1

**Comment by arnobaer** [comment]
Thank you, this seems to be an issue with the table controller.

The Corvus/Venus1 manual states the following (somewhat cryptic) description for error 1004: _"Move stopped working range should run over"_.

**Comment by arnobaer** [comment]
Got it! Error 1004 originates from the first relative Z movement performed when moving to a position using the table move dialog (performing a relative move to a value < 0 raises error 1004).

Possible workarounds could be to either clearing the 1004 error after retreating the Z axis or to perform a relative move of the current Z value, eg.
```python
z = corvus.pos.z
corvus.rmove(0, 0, -abs(z)) # safely retreat Z to zero
```
